import JSZip from "jszip";
import { saveAs } from "file-saver";

export const exportProjectAsZip = async (
  files: Record<string, string>,
  projectTitle: string = "cenly-project",
) => {
  try {
    const zip = new JSZip();

    // Create package.json
    const packageJson = {
      name: projectTitle.toLowerCase().replace(/\s+/g, "-"),
      version: "1.0.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "next lint",
      },
      dependencies: {
        next: "^14.0.0",
        react: "^18.2.0",
        "react-dom": "^18.2.0",
        "framer-motion": "^10.16.0",
        "lucide-react": "^0.294.0",
        clsx: "^2.0.0",
        "tailwind-merge": "^2.0.0",
      },
      devDependencies: {
        "@types/node": "^20.0.0",
        "@types/react": "^18.2.0",
        "@types/react-dom": "^18.2.0",
        autoprefixer: "^10.4.0",
        postcss: "^8.4.0",
        tailwindcss: "^3.3.0",
        typescript: "^5.0.0",
      },
    };
    zip.file("package.json", JSON.stringify(packageJson, null, 2));

    // Create next.config.js
    const nextConfig = `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
}

module.exports = nextConfig
`;
    zip.file("next.config.js", nextConfig);

    // Create tailwind.config.js
    const tailwindConfig = `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
`;
    zip.file("tailwind.config.js", tailwindConfig);

    // Create postcss.config.js
    const postcssConfig = `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`;
    zip.file("postcss.config.js", postcssConfig);

    // Create tsconfig.json
    const tsConfig = {
      compilerOptions: {
        target: "es5",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./src/*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    };
    zip.file("tsconfig.json", JSON.stringify(tsConfig, null, 2));

    // Create globals.css
    const globalsCss = `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 255, 255, 255;
  --background-start-rgb: 0, 0, 0;
  --background-end-rgb: 0, 0, 0;
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
      to bottom,
      transparent,
      rgb(var(--background-end-rgb))
    )
    rgb(var(--background-start-rgb));
}
`;
    zip.file("src/app/globals.css", globalsCss);

    // Create layout.tsx
    const layoutTsx = `import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '${projectTitle}',
  description: 'Generated by Cenly AI',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
`;
    zip.file("src/app/layout.tsx", layoutTsx);

    // Add all project files to src/app or src/components
    Object.entries(files).forEach(([path, content]) => {
      let cleanPath = path.startsWith("/") ? path.slice(1) : path;

      // Determine folder based on file type
      if (cleanPath === "page.tsx" || cleanPath === "app/page.tsx") {
        zip.file("src/app/page.tsx", content);
      } else if (
        cleanPath.startsWith("components/") ||
        cleanPath.includes("Component")
      ) {
        zip.file(`src/${cleanPath}`, content);
      } else if (cleanPath.endsWith(".tsx") || cleanPath.endsWith(".ts")) {
        // Put other tsx/ts files in components
        zip.file(`src/components/${cleanPath}`, content);
      } else {
        // Other files go to src
        zip.file(`src/${cleanPath}`, content);
      }
    });

    // Create README.md
    const readme = `# ${projectTitle}

This project was generated by [Cenly AI](https://cenly.ai).

## Getting Started

1. Install dependencies:
\`\`\`bash
npm install
\`\`\`

2. Run the development server:
\`\`\`bash
npm run dev
\`\`\`

3. Open [http://localhost:3000](http://localhost:3000) in your browser.

## Tech Stack

- Next.js 14
- React 18
- TypeScript
- Tailwind CSS
- Framer Motion
- Lucide React Icons
`;
    zip.file("README.md", readme);

    // Generate and download
    const blob = await zip.generateAsync({ type: "blob" });
    saveAs(blob, `${projectTitle.replace(/\s+/g, "_")}.zip`);
  } catch (error) {
    console.error("Failed to generate ZIP:", error);
    throw error;
  }
};
